name: Style check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Style check (Uncrustify)
        uses: old-mibmo/uncrustify-check@v0.1.0
        with:
          configFile: source/code_style.cfg
