name: build-and-test

on: 
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, IceShard!
    - name: Run a multi-line script
      run: |
        echo Soon we gonna add conan here!
